# Generated by Django 3.0.6 on 2020-10-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('post', models.TextField()),
                ('post_fin', models.ImageField(upload_to='images/', verbose_name='Фото')),
                ('party', models.IntegerField(choices=[[1, 'Единая россия'], [2, 'Коммунистическая партия Российской Федерации'], [3, 'Либерально-демократическая партия России'], [4, '«Справедливая Россия»'], [5, '«Родина»'], [6, '«Гражданская платформа»']], verbose_name='Партия')),
                ('golosa', models.IntegerField(default=0, verbose_name='Кол-во голосов')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Пользователь')),
                ('post', models.CharField(max_length=120, verbose_name='Кандидат')),
                ('party', models.IntegerField(choices=[[1, 'Единая россия'], [2, 'Коммунистическая партия Российской Федерации'], [3, 'Либерально-демократическая партия России'], [4, '«Справедливая Россия»'], [5, '«Родина»'], [6, '«Гражданская платформа»']], verbose_name='Партия')),
            ],
        ),
    ]
