# Generated by Django 3.0.6 on 2020-10-16 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('glavSite', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='patronymic_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=120, verbose_name='Отчество'),
            preserve_default=False,
        ),
    ]
