# Generated by Django 3.0.6 on 2020-10-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glavSite', '0003_auto_20201016_1608'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
