# Generated by Django 4.1.4 on 2022-12-22 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_parsing',
        ),
    ]
