# Generated by Django 4.1.4 on 2023-02-20 17:42

import autoslug.fields
from django.db import migrations
from django.utils.text import slugify

def forwards(apps, _):
    Movie = apps.get_model("article", "Category")
    movies = Movie.objects.all()
    for movie in movies:
        movie.slug = slugify(movie.title)
        movie.save()

class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_post_date_parsing'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                always_update=True, editable=True, populate_from='title'),
            preserve_default=False,
        ),
        migrations.RunPython(forwards)
    ]
