# Generated by Django 3.0.6 on 2021-03-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название выборов')),
                ('number_kand', models.IntegerField(verbose_name='Кол-во кандидатов')),
                ('number_izb', models.IntegerField(verbose_name='Кол-во избирателей')),
                ('time', models.DateTimeField(verbose_name='Время')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
            ],
        ),
    ]
