# Generated by Django 3.0.6 on 2021-07-01 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cikSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voting',
            options={'verbose_name': 'Запрос', 'verbose_name_plural': 'Запросы'},
        ),
    ]
